export const CLIENT_PORTAL_PATHS = {
  connexion: '/login',
  inscription: '/register',
  tableauDeBord: '/mon-compte/tableau-de-bord',
  vehicules: '/mon-compte/vehicules',
  rendezVous: '/mon-compte/rendez-vous',
  marketplace: '/mon-compte/marketplace',
  devis: '/mon-compte/devis',
  proformas: '/mon-compte/proformas',
  factures: '/mon-compte/factures',
  interventions: '/mon-compte/interventions',
  notifications: '/mon-compte/notifications',
  profil: '/mon-compte/profil',
  parametres: '/mon-compte/parametres',
} as const;
