export interface Service {
  slug: string;
  number: string;
  title: string;
  shortTitle: string;
  summary: string;
  description: string;
  image: string;
  alert: string[];
  includes: string[];
}

export const SERVICES: Service[] = [
  { slug: 'mecanique-generale', number: '01', title: 'Mécanique générale', shortTitle: 'Mécanique', summary: 'Réparations mécaniques fiables pour préserver les performances de votre véhicule.', description: 'De la recherche de panne à la réparation des organes mécaniques, notre équipe prend en charge votre véhicule avec méthode et transparence.', image: 'https://images.unsplash.com/photo-1493238792000-8113da705763?q=80&w=800&auto=format&fit=crop', alert: ['Bruits inhabituels', 'Perte de puissance', 'Fumée ou fuite visible'], includes: ['Contrôle des organes mécaniques', 'Réparation moteur et transmission', 'Remplacement des pièces défectueuses'] },
  { slug: 'diagnostic-electronique', number: '02', title: 'Diagnostic électronique', shortTitle: 'Diagnostic', summary: 'Identifiez rapidement l’origine d’un voyant ou d’une panne électronique.', description: 'Nous utilisons des outils de diagnostic adaptés pour interpréter les codes défauts et trouver la cause réelle du problème.', image: 'https://images.unsplash.com/photo-1635835694200-a4a350080648?q=80&w=800&auto=format&fit=crop', alert: ['Voyant allumé au tableau de bord', 'Démarrage difficile', 'Fonctionnement irrégulier'], includes: ['Lecture des codes défauts', 'Contrôle des calculateurs', 'Effacement des alertes après intervention'] },
  { slug: 'entretien-vidange', number: '03', title: 'Entretien & vidange', shortTitle: 'Entretien', summary: 'Les gestes essentiels pour prolonger la durée de vie de votre moteur.', description: 'Un entretien régulier protège votre véhicule, réduit les risques de panne et préserve sa valeur dans le temps.', image: 'https://images.unsplash.com/photo-1632823471565-1ec2a74c2e6f?q=80&w=800&auto=format&fit=crop', alert: ['Échéance de révision dépassée', 'Huile moteur foncée', 'Consommation anormale'], includes: ['Vidange et filtres', 'Contrôles des niveaux', 'Révision constructeur selon préconisations'] },
  { slug: 'freinage-suspension', number: '04', title: 'Freinage & suspension', shortTitle: 'Freinage', summary: 'Gardez une tenue de route et une capacité de freinage irréprochables.', description: 'Vos freins et vos suspensions jouent un rôle essentiel dans votre sécurité : nous les contrôlons et intervenons si nécessaire.', image: 'https://images.unsplash.com/photo-1486262715619-6708146fb236?q=80&w=800&auto=format&fit=crop', alert: ['Vibrations au freinage', 'Grincement ou bruit métallique', 'Véhicule instable sur route'], includes: ['Plaquettes, disques et liquide de frein', 'Amortisseurs et ressorts', 'Contrôle de sécurité complet'] },
  { slug: 'climatisation', number: '05', title: 'Climatisation', shortTitle: 'Climatisation', summary: 'Un air sain et une température agréable en toute saison.', description: 'Nous entretenons votre système de climatisation pour améliorer votre confort et la qualité de l’air dans l’habitacle.', image: 'https://images.unsplash.com/photo-1579893963473-cbcf2eb98b4b?q=80&w=800&auto=format&fit=crop', alert: ['Air qui ne refroidit plus', 'Mauvaise odeur dans l’habitacle', 'Bruit lors de l’activation'], includes: ['Contrôle du circuit', 'Recharge de gaz', 'Nettoyage et traitement antibactérien'] },
  { slug: 'electricite-batterie', number: '06', title: 'Électricité & batterie', shortTitle: 'Électricité', summary: 'Démarrage, éclairage et équipements : une installation électrique maîtrisée.', description: 'Nous vérifions la batterie, l’alternateur et les composants électriques qui assurent le bon fonctionnement de votre véhicule.', image: 'https://images.unsplash.com/photo-1621217736657-3a139a066440?q=80&w=800&auto=format&fit=crop', alert: ['Démarrage lent ou impossible', 'Phares faibles', 'Équipements électriques défaillants'], includes: ['Test de batterie', 'Contrôle alternateur et démarreur', 'Réparation des circuits électriques'] },
  { slug: 'carrosserie-peinture', number: '07', title: 'Carrosserie & peinture', shortTitle: 'Carrosserie', summary: 'Redonnez à votre véhicule son allure et protégez durablement sa carrosserie.', description: 'Après un choc, une rayure ou l’usure du temps, nos interventions restaurent l’aspect et la protection de votre véhicule.', image: 'https://images.unsplash.com/photo-1590498305417-640a3dd90dcb?q=80&w=800&auto=format&fit=crop', alert: ['Rayures et impacts', 'Élément déformé', 'Peinture écaillée'], includes: ['Débosselage et redressage', 'Préparation des surfaces', 'Peinture et finitions'] },
  { slug: 'pneumatiques', number: '08', title: 'Pneumatiques', shortTitle: 'Pneus', summary: 'La bonne adhérence commence par des pneus en parfait état.', description: 'Nous vous accompagnons dans le contrôle, le choix et l’entretien de vos pneus pour une conduite sereine.', image: 'https://images.unsplash.com/photo-1600705722908-bab1e61c0b4d?q=80&w=800&auto=format&fit=crop', alert: ['Usure irrégulière', 'Perte de pression fréquente', 'Vibrations dans le volant'], includes: ['Contrôle d’usure et pression', 'Montage et équilibrage', 'Conseil sur le choix des pneus'] },
  { slug: 'remorquage', number: '09', title: 'Remorquage', shortTitle: 'Remorquage', summary: 'Une assistance rapide pour ne jamais rester bloqué sur la route.', description: 'En cas d’immobilisation, nous organisons la prise en charge de votre véhicule et son acheminement vers l’atelier.', image: 'https://images.unsplash.com/photo-1520624029259-71ee51a1d137?q=80&w=800&auto=format&fit=crop', alert: ['Panne immobilisante', 'Accident ou crevaison', 'Véhicule impossible à démarrer'], includes: ['Prise en charge du véhicule', 'Acheminement vers l’atelier', 'Coordination de votre intervention'] },
];
