import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth.interceptor';

import { routes } from './app.routes';

import {
  provideLucideIcons,
  LucideHouse,
  LucideUsers,
  LucideCar,
  LucidePackage,
  LucideReceipt,
  LucideCalculator,
  LucideSettings,
  LucideLogOut,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronLeft,
  LucideChevronUp,
  LucideSearch,
  LucidePlus,
  LucideMinus,
  LucidePencil,
  LucideTrash2,
  LucideX,
  LucideEye,
  LucideEyeOff,
  LucideCheck,
  LucideCheckCircle,
  LucideAlertTriangle,
  LucideXCircle,
  LucideClock,
  LucideArrowRight,
  LucideArrowLeft,
  LucideDownload,
  LucideUpload,
  LucideLoader2,
  LucideUser,
  LucideLock,
  LucideCalendar,
  LucidePhone,
  LucideMail,
  LucideTag,
  LucideBuilding2,
  LucideArchive,
  LucideArchiveRestore,
  LucideWrench,
  LucideClipboardList,
  LucideRefreshCw,
  LucidePercent,
  LucideFileCheck,
  LucideFileText,
  LucidePrinter,
  LucideFilter,
  LucideSlidersHorizontal,
  LucideTruck,
  LucideBell,
  LucideAlertCircle,
  LucideInfo,
  LucideShieldCheck,
  LucideCog,
  LucideBarChart2,
  LucidePlusCircle,
  LucideRotateCcw,
  LucideSave,
  LucideCopy,
  LucideCircle,
  LucideMapPin,
  LucideMoreHorizontal,
} from '@lucide/angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withInMemoryScrolling({ scrollPositionRestoration: 'enabled' })),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideLucideIcons(
      LucideHouse,
      LucideUsers,
      LucideCar,
      LucidePackage,
      LucideReceipt,
      LucideCalculator,
      LucideSettings,
      LucideLogOut,
      LucideChevronDown,
      LucideChevronRight,
      LucideChevronLeft,
      LucideChevronUp,
      LucideSearch,
      LucidePlus,
      LucideMinus,
      LucidePencil,
      LucideTrash2,
      LucideX,
      LucideEye,
      LucideEyeOff,
      LucideCheck,
      LucideCheckCircle,
      LucideAlertTriangle,
      LucideXCircle,
      LucideClock,
      LucideArrowRight,
      LucideArrowLeft,
      LucideDownload,
      LucideUpload,
      LucideLoader2,
      LucideUser,
      LucideLock,
      LucideCalendar,
      LucidePhone,
      LucideMail,
      LucideTag,
      LucideBuilding2,
      LucideArchive,
      LucideArchiveRestore,
      LucideWrench,
      LucideClipboardList,
      LucideRefreshCw,
      LucidePercent,
      LucideFileCheck,
      LucideFileText,
      LucidePrinter,
      LucideFilter,
      LucideSlidersHorizontal,
      LucideTruck,
      LucideBell,
      LucideAlertCircle,
      LucideInfo,
      LucideShieldCheck,
      LucideCog,
      LucideBarChart2,
      LucidePlusCircle,
      LucideRotateCcw,
      LucideSave,
      LucideCopy,
      LucideCircle,
      LucideMapPin,
      LucideMoreHorizontal,
    ),
  ]
};
